language: objective-c
osx_image: xcode8.3
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update
branches:
  only:
  - master
  - develop
script:
  - set -o pipefail
  - xcodebuild -workspace Gank.xcworkspace -scheme Gank -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
